<?php
# This file was automatically generated by the MediaWiki 1.35.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "SonderForschungsBereich 1153";
$wgMetaNamespace = "SonderForschungsBereich_1153";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/sfb1153/wiki";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://service.tib.eu";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;
# BEGIN added by ansible #
$wgArticlePath = "/sfb1153/wiki/$1";
$wgUsePathInfo = true;
# END added by ansible #

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/wiki.png" ];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "lab.lsk@tib.eu";
$wgPasswordSender = "lab.lsk@tib.eu";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "";
$wgDBname = "sfb1153mw";
$wgDBuser = "sfb1153mwuser";
$wgDBpassword = "SFB1153wikiDB";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = false;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale. This should ideally be set to an English
## language locale so that the behaviour of C library functions will
## be consistent with typical installations. Use $wgLanguageCode to
## localise the wiki.
$wgShellLocale = "C.UTF-8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "53293367aa31c4a94531849d1e7e9f09652ab1535211a9545a05d56b1db65451";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "2f47ff4d9b2845d3";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );


# End of automatically generated settings.
# Add more configuration options below.

# BEGIN ANSIBLE MANAGED BLOCK
# Job are run by cron
$wgJobRunRate = 0;
# Permissions
$wgGroupPermissions['*']['read'] = false;
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['user']['edit'] = true;
$wgGroupPermissions['*']['createaccount'] = false;
# uploads
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";
$wgFileExtensions = array( 'pdf', 'png', 'gif', 'jpg', 'jpeg', 'svg', 'pdf', 'mp4', 'mp3' );
$wgAllowExternalImages = true;
$wgMaxUploadSize = 20971520;  # 20Mb;
$wgUploadSizeWarning = 20971520;
$wgAllowCopyUploads = true;
$wgGroupPermissions['user']['upload_by_url'] = true; # Uploading directly from a URL
$wgCopyUploadsFromSpecialUpload = true;
# Debug
$wgShowExceptionDetails=true;
$wgShowSQLError=true;
$wgShowDBErrorBacktrace=true;
error_reporting(-1);
ini_set('display_errors',1);
# END ANSIBLE MANAGED BLOCK

# -- fix for CVE-2021-44858, CVE-2021-45038, CVE-2021-44857
# fixed in 1.35.5, 1.36.3, and 1.37.1
# see https://www.mediawiki.org/wiki/2021-12_security_release/FAQ
$wgActions['mcrundo'] = false;
$wgActions['mcrrestore'] = false;
$wgWhitelistRead = [];
$wgWhitelistReadRegexp = [];
# ====

wfLoadExtension( 'Bootstrap' );
wfLoadSkin( 'chameleon' );
$wgDefaultSkin='chameleon';
# Layout:
$egChameleonLayoutFile = __DIR__ . '/skins/chameleon/layouts/custom.xml';
# Style:
$egChameleonExternalStyleModule =  __DIR__ . '/skins/chameleon/resources/styles/custom.scss';

# Cite
wfLoadExtension('Cite');

# CodeEditor
wfLoadExtension('CodeEditor');
$wgDefaultUserOptions['usebetatoolbar'] = 1;


# Renameuser
wfLoadExtension('Renameuser');

# SyntaxHighlight_GeSHi
wfLoadExtension('SyntaxHighlight_GeSHi');
$wgSyntaxHighlightModels['CONTENT_MODEL_SCRIBUNTO'] = 'lua';

# WikiEditor
wfLoadExtension( 'WikiEditor' );

# Scribunto
wfLoadExtension( 'Scribunto' );
$wgScribuntoDefaultEngine = 'luastandalone';
$wgScribuntoUseGeSHi = true;
$wgScribuntoUseCodeEditor = true;

# SpamBlacklist
wfLoadExtension( 'SpamBlacklist' );

# Nuke
wfLoadExtension( 'Nuke' );

# Semantic Mediawiki
enableSemantics( 'https://service.tib.eu/sfb1153/wiki/', true );
$smwgShowFactbox=true;
$smwgFieldTypeFeatures=SMW_FIELDT_CHAR_NOCASE;
$smwgQMaxInlineLimit=1500;
$smwgQMaxInlineLimitSets=1500;
$smwgPageSpecialProperties=array_merge($smwgPageSpecialProperties, ['_LEDT', '_CDAT', '_NEWP' ]);
#$wgCapitalLinks=false;
$smwgChangePropagationProtection=false;

# Semantic Cite
wfLoadExtension( 'SemanticCite' );

# Semantic Result Formats
wfLoadExtension( 'SemanticResultFormats' );

# Maps
wfLoadExtension( 'Maps' );

# PageForms
wfLoadExtension( 'PageForms' );
$wgPageFormsAutocompleteOnAllChars = true;
$wgPageFormsMaxLocalAutocompleteValues = 100;
$wgPageFormsMaxAutocompleteValues = 1000000;

# ParserFunctions
wfLoadExtension( 'ParserFunctions' );
$wgPFEnableStringFunctions = true;

# Interwiki
wfLoadExtension( 'Interwiki' );
$wgGroupPermissions['sysop']['interwiki'] = true;

# AdminLinks
wfLoadExtension( 'AdminLinks' );

# ReplaceText
wfLoadExtension( 'ReplaceText' );

# SemanticDrilldown
require_once "$IP/extensions/SemanticDrilldown/SemanticDrilldown.php";

# ConfirmAccount
require_once "$IP/extensions/ConfirmAccount/ConfirmAccount.php";
$wgConfirmAccountRequestFormItems["Biography"]["enabled"] = false;
$wgWhitelistRead = array( "Special:RequestAccount" );
$wgGroupPermissions["bureaucrat"]["confirmaccount-notify"] = true;

# MyVariables
wfLoadExtension( 'MyVariables' );

# AutoCreatePage
# require_once "$IP/extensions/AutoCreatePage/AutoCreatePage.php";
wfLoadExtension('AutoCreatePage');
$egAutoCreatePageOnSpecialPages[] = 'RunQuery';


# Arrays
wfLoadExtension( 'Arrays' );

# LookupUser
wfLoadExtension( 'LookupUser' );
$wgGroupPermissions['*']['lookupuser'] = false;
$wgGroupPermissions['sysop']['lookupuser'] = true;

# CodeMirror
wfLoadExtension('CodeMirror');
$wgDefaultUserOptions['usecodemirror']=1;

## Custom Namespaces
define("NS_TERM", 3000); 
define("NS_TERM_TALK", 3001);

$wgExtraNamespaces[NS_TERM] = "Term";
$wgExtraNamespaces[NS_TERM_TALK] = "Term_talk"; 

$smwgNamespacesWithSemanticLinks[NS_TERM] = true;
$smwgNamespacesWithSemanticLinks[NS_TERM_TALK] = true;

$wgEnableParserCache = false; // deprecated method
$wgParserCacheType = CACHE_NONE;
$wgCachePages = false;

wfLoadExtension('MwJson');
wfLoadExtension('InteractiveSemanticGraph');

# connection to triplestore
#smwgDefaultStore = 'SMWSparqlStore';
#$smwgSparqlRepositoryConnector = 'fuseki';
#$smwgSparqlEndpoint["query"] = 'http://sparql21.service.tib.eu/fuseki/smw1153/query';
#$smwgSparqlEndpoint["update"] = 'http://sparql21.service.tib.eu/fuseki/smw1153/update';
#$smwgSparqlEndpoint["data"] = '';

#Display Title Extension
wfLoadExtension('DisplayTitle');
$wgAllowDisplayTitle = true;
$wgRestrictDisplayTitle = false;

# EditAccount
wfLoadExtension( 'EditAccount' );
$wgGroupPermissions['bureaucrat']['editaccount'] = true;
$wgGroupPermissions['editaccount']['editaccount'] = true;

# UserMerge
wfLoadExtension( 'UserMerge' );
$wgGroupPermissions['bureaucrat']['usermerge'] = true;
