name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: make ci
      - uses: actions/upload-artifact@v3
        with:
          name: BackstopJS
          path: backstop/backstop_data
        if: always()
